var anglais=["ABBA - Gimme! Gimme! Gimme! (A Man After Midnight)",
"ABBA - Mamma Mia",
"ABBA - Money Money Money",
"ABBA - Voulez Vous",
"ACDC - Shoot to thrill",
"Amy Winehouse - Back To Black [VIDEO]",
"Amy Winehouse - Rehab",
"Amy Winehouse - Tears Dry On Their Own",
"Amy Winehouse - You Know I'm No Good",
"Anggun & Laurent Wolf - No Stress",
"Aqua - Barbie Girl",
"Ariana Grande - 7 Rings",
"Ariana Grande - Thank u, next (MV)",
"Armin van Buuren - Blah Blah Blah",
"AronChupa - Im an Albatraoz",
"Arsenium - Love Me Love Me",
"Avicii - Hey Brother",
"Avicii - Wake Me Up!",
"Barry White - Can't Get Enough Of Your Love Baby",
"Beyonce - Crazy In Love",
"Beyoncé - Single ladies (Put a ring on it)",
"Billie Eilish - Bad Guy",
"Black Eyed Peas - Boom Boom Pow",
"Black Eyed Peas - I Gotta Feeling",
"Black Eyed Peas - My humps",
"Black Eyed Peas - Pump It",
"Boney M - Daddy Cool",
"Boney M. - Rasputin",
"Britney Spears - Baby One More Time",
"Britney Spears - Circus",
"Britney Spears - Gimme More",
"Britney Spears - I Wanna Go",
"Britney Spears - Oops! I did it again",
"Britney Spears - Piece Of Me",
"Britney Spears - Toxic",
"Britney Spears - Womanizer",
"Bruno Mars - 24K Magic",
"Bruno Mars - Treasure",
"Captain Jack - Captain Jack",
"Carl Douglas - Kung Fu Fighting [VIDEO]",
"Cartoons - Witch Doctor",
"Cher -  GIMME GIMME GIMME (A Man After Midnight)",
"Cher - Music's No Good",
"Cinema Bizarre - Lovesongs (They Kill Me)",
"Coldplay - A Sky Full of Stars [VIDEO]",
"Coldplay - Paradise",
"Coldplay - Viva la vida",
"Coldplay feat. Rihanna - Princess Of China",
"Coumba Gawlo - Pata pata",
"Daddy DJ - Daddy DJ [VIDEO]",
"Daft Punk - Around The World",
"Daft Punk - Get Lucky",
"Daft Punk - One More Time",
"Daft Punk - Technologic",
"Daft Punk ft. Julian Casablancas - Instant Crush",
"Daft Punk ft. Pharrell - Lose Yourself to Dance",
"David Bowie - Changes",
"David Bowie - Let's Dance",
"David Bowie - Life On Mars",
"David Bowie - Starman",
"David Guetta & Chris Willis ft. Fergie & LMFAO - Gettin' over You",
"David Guetta feat. Chris Willis - Love Is Gone [VIDEO]",
"David Guetta feat. Rihanna - Who's That Chick",
"Destiny's Child - Survivor [VIDEO]",
"Eiffel 65 - Blue",
"Electric Light Orchestra - Mr. Blue Sky",
"Elton John - I'm Still Standing",
"Elvis Presley - Jailhouse Rock",
"Eminem & Rihanna - The Monster",
"Enrique Iglesias ft Nadiya Tired of Being Sorry",
"Eric Prydz - Call on me",
"Europe - Final Countdown",
"Evanescence - Bring Me to Life",
"Gene Vincent - Be Bop A Lula",
"Genesis - Keep It Dark",
"Genesis - mama",
"George Benson - Give Me The Night",
"Jain - Come",
"Jain - Makeba",
"Jakarta - One Desire [VIDEO]",
"Jean-Denis Perez - Just because of you",
"Jeff Buckley - Hallelujah",
"Jennifer Lopez & Pitbull - On The Floor",
"Jessie J, Ariana Grande & Nicki Minaj - Bang Bang",
"Justin Timberlake - SexyBack",
"Kat Deluna Feat. Elephant Man - Whine Up",
"Katy Perry - I Kissed A Girl",
"Katy Perry feat. Nicki Minaj - Swish Swish",
"Kirin J Callinan - Big Enough ft. Alex Cameron, Molly Lewis, Jimmy Barnes",
"Lady Gaga & Ariana Grande - Rain On Me",
"Lady GaGa - Bad Romance",
"Lady GaGa - Born this way",
"Lady GaGa - Judas",
"Lady GaGa - Megamix (Extended Mix)",
"Lady GaGa - Paparazzi",
"Lady Gaga - Poker Face",
"Lady Gaga - Stupid Love",
"Lady GaGa feat. Beyoncé - Telephone",
"Lady Gaga, Bradley Cooper - Shallow",
"Lil Nas X feat. Billy Ray Cyrus - Old Town Road",
"LMFAO - Sexy and I Know It",
"LMFAO feat. Natalia Kills - Champagne Showers",
"Lou Bega - Mambo No. 5 (A Little Bit Of...)",
"LP - Lost on you",
"Madonna - Hung Up",
"Madonna - Jump",
"Madonna - Like a Virgin [VIDEO]",
"Madonna - Sorry",
"Madonna feat. Justin Timberlake - 4 Minutes",
"Mariah Carey - All I Want For Christmas Is You",
"Marilyn Manson - Personal Jesus",
"Marilyn Manson - Sweet Dreams",
"Marilyn Manson - Tainted Love",
"Mark Ronson feat. Bruno Mars - Uptown Funk",
"Maroon 5 - This Love",
"Maroon 5 ft. Cardi B - Girls Like You",
"Martin Solveig - Everybody",
"Martin Solveig feat. Dragonette - Hello",
"Michael Jackson - Bad",
"Michael Jackson - Billie Jean",
"Michael Jackson - Black or white",
"Michael Jackson - Blood On The Dance Floor",
"Michael Jackson - Dirty Diana",
"Michael Jackson - Don't stop till you get enough",
"Michael Jackson - Ghost",
"Michael Jackson - Heal the world",
"Michael Jackson - Rock with you",
"Michael Jackson - Smooth Criminal",
"Michael Jackson - The Way You Make Me Feel",
"Michael Jackson - They don't care about us",
"Michael Jackson - Thriller",
"Miley Cyrus - Wrecking Ball",
"Moby - Lift me up",
"Nirvana - Come As You Are",
"Nirvana - Lithium",
"Nirvana - Rape Me",
"Nirvana - Stay away",
"Ocean Drive - without you",
"Owl City - Fireflies",
"Patrick Hernandez - Born To Be Alive",
"Pharrell Williams - Happy",
"Phats & Small - Turn Around",
"Piko Taro - Pen Pineapple Apple Pen",
"Pitch  - Move Your Body",
"Purple Disco Machine, Sophie and the Giants - Hypnotized",
"Pussycat Dolls - Hush Hush",
"Queen - Another One Bites the Dust",
"Queen - Bohemian Rhapsody",
"Queen - I Want to Break Free",
"Queen - Keep yourself alive",
"Queen - Lazing on a Sunday afternoon",
"Queen - Radio Ga Ga",
"Queen - Spread Your Wings",
"Queen - Under Pressure",
"Queen - We Are the Champions",
"Queen - We Will Rock You",
"Ray Charles - Hit the Road Jack",
"Redbone - Come and get your Love",
"Richard Sanderson - Reality",
"Rick Astley - Never gonna give you up",
"Ricky Martin - Maria",
"Rihanna - Diamonds",
"Rihanna - Don't stop the music",
"Rihanna - Pon De Replay",
"Rihanna - Rude Boy",
"Rihanna - Russian roulette",
"Rihanna - Shut Up And Drive",
"Rihanna - Umbrella [VIDEO]",
"Rihanna - We Ride",
"Roberto Blanco vs. The Disco Boys - Born To Be Alive",
"Samantha Fox - Nothing's gonna stop me now",
"Scatman John - Scatman (Ski-Ba-Bop-Ba-Dop-Bop)",
"Sean Paul - Temperature",
"Selena Gomez - Slow Down",
"SHAKA PONK - My name is Stain",
"Shakira & Rihanna - Can't Remember to Forget You",
"Shakira - Je l'aime à mourir",
"Shakira ft. Freshlyground - Waka Waka (This Time for Africa)",
"Spice Girls - 2 Become 1",
"Spice Girls - Mama",
"Spice Girls - Say You'll Be There",
"Spice Girls - Spice Up Your Life",
"Spice Girls - Stop",
"Spice Girls - Too Much",
"Spice Girls - Viva forever",
"Spice Girls - Wannabe",
"Spice Girls - Who do you think you are",
"Survivor - Eye Of The Tiger",
"t.A.T.u. - All the things she said",
"The Kinks - You Really Got Me",
"The Weeknd - Blinding Lights",
"The Weeknd ft. Daft Punk - I feel it coming",
"Tibz - Nation",
"Tones And I - Dance Monkey",
"Van Halen - Jump",
"Van Halen - You Really Got Me",
"Vengaboys - Boom, Boom, Boom, Boom!!",
"Verka Serduchka - Dancing Lasha Tumbai",
"Village People - In the Navy",
"Village People - Macho man",
"Village People - YMCA",
"Wham - Wake Me Up Before You Go-Go",
"Wham! - Everything she wants",
"Wham! - Last Christmas",
"Whitney Houston - I Will Always Love You",
"will.i.am & Britney Spears - Scream and Shout",
"Wings - Mull of Kintyre",
"£1 Fish Man - One Pound Fish - O-Fish-Al Video", ]

var francais=[
"Christophe Mae - La vie dartiste",
"Chritophe Maé feat Youssou N'Dour - L'ours",
"Clara Lucciani - La baie",
"Claudio Capéo - C'est une chanson",
"Coeur de pirate - T'es belle",
"Flo Delavega - Printemps éternel",
"Hoshi - Amour censure",
"Indochine - Nos célébrations",
"Julien Doré - La fièvre",
"Julien Doré - Nous",
"Keen'V feat Magic System - Quoi qu'il arrive",
"Kendji Girac - Habibi",
"Lartiste - Comme avant",
"LEJ - Tous les deux",
"Les enfoirés - A côté de toi",
"Louane - Donne moi ton coeur",
"Louane - Peut-être",
"Louane - Poésie indécise",
"M Pokora - Danse avec moi",
"M. Pokora - Si on disait",
"Madame Monsieur ft Jeremy Frerot- Comme un voleur",
"Mika & Soprano - Le coeur holiday",
"Mylène Farmer - L'âme dans l'eau",
"Patrick Fiori & Florent Pagny- J'y vais",
"Patrick Fiori - Un air de famille",
"Tayc - N'y pense plus",
"Tryo - Serre moi 2020",
"Valentina - J'imagine",
"Vianney - Merci pour ça",
"Vianney - N'attendons pas",
"Vitaa & Slimane - Ça ira",
"Ycare Axelle Red -  I Dont Care (je m'en moque)",
"Ycare et Axelle Red - A toi",    
"-M- - Je dis aime",
"113 - Au summum",
"113 - Tonton Du Bled",
"1789 Les Amants de la Bastille - Je veux le monde",
"2 Be 3 - La Salsa",
"2 Be 3 - Toujours la pour toi",
"2be3 - 2be3",
"2be3 - Partir un jour",
"3 Cafés Gourmands - À nos souvenirs",
"47TER - On avait dit",
"Akhenaton - J'ai pas de face",
"Alain Bashung - Osez Joséphine",
"Alain Chamfort - Les Beaux Yeux de Laure",
"Alain Delorme - J'ai un petit faible pour toi",
"Alain Souchon - Foule sentimentale",
"Alain Souchon - Ici et là",
"Alain Souchon - L'amour à la machine",
"Alain Souchon - Le Bagad De Lann Bihouë",
"Alain Souchon - Le Baiser",
"Aldebert feat Jeanne Cherhal - On n'est pas là pour se faire engueuler",
"Alexa Leclere - Avec toi contre toi",
"Alizee - Mademoiselle Juliette [VIDEO]",
"Alizée - J´en Ai Marre",
"Alizée - Moi... Lolita",
"Alliage - Baila",
"Alliage - Le temps qui court",
"Alliel - Ce qui nous rend fous",
"Alliel - Encore",
"Alphonse Brown - Le Frunkp",
"Amel Bent & Soprano - Quand La Musique Est Bonne",
"Amel Bent - Ma Philosophie",
"Amel Bent - nouveau francais",
"Amine - J'voulais",
"Amine - J'voulais [VIDEO]",
"Amine - My Girl",
"Amir - Au coeur de moi",
"Amir - I know",
"Amir - Il est tant que l'on s'aime",
"Amir - J'ai cherché",
"Amir - La fête",
"Amir - Lost",
"Amir - On dirait",
"Amir - On verra bien",
"Amir-Je Reviendrai",
"Amir-Très haut",
"Anaïs - Mon Coeur Mon Amour [VIDEO]",
"Anaïs - Mon Coeur, Mon Amour",
"Angelina - Maman me dit",
"Anggun - Echo",
"Anggun - Être une femme",
"Angèle - Balance ton quoi",
"Angèle - Flou",
"Angèle - La thune",
"Angèle - Oui Ou Non",
"Angèle feat. Roméo Elvis - Tout Oublier",
"Annie Cordy - Cho ka ka o",
"Annie Cordy - La bonne du curé",
"Assia - Elle est toi",
"Au Bonheur Des Dames - Oh! Les filles",
"Au P'Tit Bonheur - J'Veux Du Soleil",
"Axelle Red - Sensualité [VIDEO]",
"Aya Nakamura - Djadja",
"Aya Nakamura - Jolie nana",
"Aya Nakamura - Soldat",
"Bandolero - Paris Latino",
"BB Brunes - Coups et blessures",
"BB Brunes - Dis-Moi",
"Beaulieu - Eddy de Pretto",
"Ben L'Oncle Soul - Soulman",
"Benny B. - Vous êtes fous",
"Bezu - la Queuleuleu",
"Bigflo & Oli - Coup de blues; Soleil",
"Bigflo & Oli - Dommage",
"Billy Ze Kick - Mangez-Moi! Mangez-Moi!",
"Black M -  Mon beau-frère",
"Black M - Le prince Aladin ft. Kev Adams",
"Black M - madame Povosko",
"Black M - Sur ma route",
"Black mamba - Ghetto Millionnaire",
"Booba - Caramel",
"Boulevard des airs - Emmène-moi",
"Boulevard des Airs - Tu seras la dernière",
"Boulevard des airs ft. Vianney - Allez reste",
"Bourvil - La tactique du gendarme",
"Bourvil - La tendresse",
"Bourvil - Salade de fruits",
"Bourvil - Un clair de lune à Maubeuge",
"Bourvil- Adada",
"Bratisla Boys - Stach stach",
"Brett - 3 nuit par semaine",
"Brigitte Bardot - Harley Davidson",
"Bénabar - L'Effet Papillon",
"Bénabar - Le dîner",
"C Jerome - Et tu danses avec lui",
"C Jerome - Kiss Me",
"Calogero - Celui d'en bas",
"Calogero - En Apesanteur",
"Calogero - J'ai le droit aussi",
"Calogero - Je joue de la musique",
"Calogero - La rumeur",
"Calogero - Le portrait",
"Calogero - Voler de nuit",
"Calogero et Passi - Face à la mer",
"Calogero et Stanislas - La Débacle des Sentiments",
"Camélia Jordana - Non, non, non (écouter Barbara)",
"Carla - Bim bam toi",
"Carla - L'autre moi",
"Carlos - Big Bisou",
"Carlos - tous nu et tous bronzé",
"Caroline Loeb - C'est la ouate",
"Celine Dion - S'il suffisait d'aimer",
"Celine Dion En Duo Avec Garou - Sous Le Vent [VIDEO]",
"Celkilt - Petit papa Noël",
"Chagrin d'Amour - Chacun fait c'qui lui plait",
"Chanson Plus Bifluoree - Jesus viendra pour les vacances",
"Chantal Goya - Un lapin",
"Charles Aznavour - Emmenez-moi",
"Charles Aznavour - For me formidable",
"Charles Aznavour - Je me voyais déjà",
"Charles Aznavour - La Boheme",
"Charles Aznavour - Mes Emmerdes",
"Charles Trenet - Y'a de la joie",
"Chimene Badi - Je viens du sud",
"Chimène Badi - Entre Nous",
"Chris Prolls - Je suis muzik",
"Chris Prolls - Je suis Muzik (version CD)",
"Christophe - les mots bleus",
"Christophe Mae - Belle Demoiselle [VIDEO]",
"Christophe Mae - On S'attache [VIDEO]",
"Christophe Mae - Parce qu'on sait jamais [VIDEO]",
"Christophe Maé - Il est où le bonheur",
"Christophe Maé - Tombé Sous Le Charme",
"Christophe Willem - Berlin",
"Christophe Willem - Double Je",
"Christophe Willem - Double Je [VIDEO]",
"Christophe Willem - Elu produit de l'annee",
"Christophe Willem - Jaques A Dit [VIDEO]",
"Christopher Rippert - Tu me fais vraiment craquer",
"Cindy Sander - Papillon de lumiere",
"Clara Luciani - La grenade",
"Clara Morgane - Sexy Girl",
"Clara Morgane feat. Lord Kossity - J´aime",
"Claude Barzotti - Le rital",
"Claude Francois - Alexandrie Alexandra",
"Claude Francois - Chanson populaire",
"Claude Francois - Comme d'habitude",
"Claude Francois - Le Chanteur Malheureux",
"Claude Francois - Le lundi au soleil",
"Claude Francois - Le mal aimé",
"Claude Francois - Si j'avais un marteau",
"Claude François - belle, belle, belle",
"Claude François - Cette anné là",
"Claude François - Je vais à Rio",
"Claude François - Magnolias For Ever",
"Claudio Capéo - Dis-le moi",
"Claudio Capéo - Plus haut",
"Claudio Capéo - Ta main",
"Claudio Capéo - Un homme debout",
"Claudio Capéo - Ça va ça va",
"Club Dorothée - C'est toujours les vacances",
"Coeur De Pirate - Comme Des Enfants",
"Collectif Metisse - Laisse tomber tes problemes",
"Coluche - J'tape un doigt",
"Cookie Dingler - Femme Libérée [VIDEO]",
"Corbier - Laissez les mamies faire",
"Corbier - Sans ma barbe",
"Corneille- Parce qu'on vient de loin",
"Corynne Charby - Boule de flipper",
"Céline Dion & Garou - Sous le vent",
"Céline Dion - Pour Que Tu M'Aimes Encore",
"Céphaz - Depuis toi",
"Dalida & Serge lama",
"Dalida - Il venait d'avoir dix-huit ans",
"Dalida - Itsi, bitsi, petit bikini",
"Dalida - Laissez-moi danser",
"Damien Sargue - Un jour",
"Daniel Balavoine - Je ne suis pas un heros",
"Daniel Balavoine - L'Aziza",
"Daniel Balavoine - Le chanteur",
"Daniel Balavoine - Mon fils ma bataille",
"Daniel Balavoine - Quand on arrive en ville (Starmania)",
"Daniel Balavoine - Tous les cris, les SOS",
"Daniel Lévi - L'envie d'aimer",
"Dany Brillant - Quand je vois tes Yeux",
"Dany Brillant - Suzette",
"Dave - Du coté de chez Swann",
"Dave - Vanina",
"Demis Roussos - On ecrit sur les murs",
"Desireless - Voyage, voyage",
"Dezil' - San Ou (La Rivière) [VIDEO]",
"Diam's - DJ",
"Diam's - Jeune demoiselle",
"Diam's - La Boulette",
"Dick RIVERS - J'ai pas la cote avec toi",
"Dick Rivers - jericho",
"Dick RIVERS - Maman n'aime pas ma musique",
"Dick Rivers - Nice baie des anges",
"Didier Bourdon - On peuplu rien dire",
"Discobitch-c'est beau la bourgoisie",
"DIVA FAUNE FT. LEA PACI - GET UP (French Edit)",
"DJ Bobo - Chihuahua 2002",
"Dj commander - Oui sergent",
"DJ Zus vs Saint Mathieu _ Jesus Reviens",
"Doc Gyneco - Ne ici",
"Dolly - Je N'veux Pas Rester Sage [VIDEO]",
"Dorothee - Allo allo monsieur l'ordinateur",
"Dorothée - Hou la menteuse",
"Dorothée - La valise",
"Début De Soirée - La Vie La Nuit",
"Début De Soirée - Nuit De Folie",
"Eddy de Pretto - Fête de trop",
"Eddy Mitchell - Couleur menthe à l'eau",
"Eddy Mitchell - La Dernière Séance",
"Eddy Mitchell - Pas de boogie woogie",
"Eddy Mitchell - Sur la route de Memphis",
"Edith Piaf - La Vie En Rose",
"Edith Piaf - Milord",
"Edith Piaf - Non je ne regrette rien",
"Elisa Tovati & Tom Dice - Il Nous Faut [VIDEO]",
"Elli Medeiros - Toi mon toit",
"Elsa & Glenn Medeiros- Un roman d'amitié",
"Emile et Image - Les Demons De Minuit",
"Emile et Image - Maitresse",
"Emma Daumas - Tu seras",
"Emmanuel Moire - Beau malheur",
"Emmanuel Moire - Je fais de toi mon essentiel",
"Enrico Macias - Enfants de tous pays",
"Enrico Macias - Les Filles De Mon Pays",
"ERA - Ameno",
"Eric Morena - Oh mon bateau",
"Etienne Daho & Dani - Comme Un Boomerang",
"Fatal Bazooka - Ce soir, Sans mon SEXE",
"Fatal Bazooka - Fous ta cagoule",
"Fatal Bazooka - Trankillement",
"Fatal Bazooka feat Vitoo - Mauvaise foi nocturne",
"Fatal Bazooka vs Chris Prolls - Super Clash",
"Faudel - Mon pays",
"Florent Mothe (Mozart L'Opéra Rock) - L'assasymphonie",
"Florent Mothe - Le Bien Qui Fait Mal",
"Florent Pagny - Chanter",
"Florent Pagny - Châtelet les halles (live à l'olympia 2003)",
"Florent Pagny - Combien De Gens",
"Florent Pagny - Le Soldat",
"Florent Pagny - Là où Je t'emmènerai",
"Florent Pagny - Ma liberté de penser",
"Florent Pagny - N'importe Quoi",
"Florent Pagny - Savoir Aimer",
"Florent Pagny - Si tu veux m'essayer",
"France Gall - Babacar",
"France Gall - Débranche",
"France Gall - Evidemment",
"France Gall - Il Jouait Du Piano Debout",
"France Gall - La chanson de Maggie",
"France Gall - Poupée de cire, poupée de son",
"France Gall - Résiste",
"France Gall - Sacré Charlemagne",
"France Gall - Si, maman, si",
"France-Gall - laisse tomber les filles",
"Francis Cabrel - Encore et encore",
"Francis Cabrel - Je l'aime à mourir",
"Francis Cabrel - Petite Marie",
"Francis Cabrel - Soldat Rose - Gardien de nuit",
"Francky Vincent - Alice Ca Glisse",
"Francky Vincent - Fruit de la passion",
"Francky Vincent - Tu veux mon zizi",
"Francois Valéry - Aimons-nous vivants",
"Frank Alamo - Biche Oh Ma Biche",
"FRANK ALAMO Allo Maillot 38-37",
"François Feldman - Je te retrouverai",
"François Valéry - Emmanuelle",
"Freddy Gladieux - Mirador (feat. Kezah)",
"Frederic Francois - Je T'aime A L'italienne",
"FREHEL - La java bleue",
"Fréro Delavega - Autour de moi",
"Fréro Delavega - Le chant des Sirènes",
"Fréro Delavega - Ton visage",
"Félicien - Cum-Cum Mania",
"Gad Elmaleh & LiMa Project Danse de la joie (Lalala) - Clip Officiel",
"Gamine - Voilà les anges",
"Garou - Seul",
"Gerald De Palmas - J'en rêve encore",
"Gilbert Montagné - Les Sunlights des Tropiques",
"Gilbert Montagné - On va s'aimer",
"GIMS & Sting - Reste",
"Gims - Jusqu'ici tout va bien",
"Gims - Malheur malheur",
"Gold - Calicoba",
"Gold - Capitaine Abandonné",
"Gold - Laissez-nous chanter",
"Gold - Plus près des étoiles",
"Gradur ft. Heuss L'enfoiré -  Ne reviens pas",
"Gregoire - Toi plus Moi",
"Grégoire - Danse [VIDEO]",
"Grégoire - Le Même Soleil [VIDEO]",
"Grégoire - Ta Main [VIDEO]",
"Guy Marchand - Destinée (1982)",
"Gérard Blanc - Une autre histoire",
"Gérard Lenorman - La ballade des Gens Heureux",
"Gérard Lenorman - Voici les Clés",
"Harley Davidson",
"Hatik - Angela",
"Helene Rolles - Je m'appelle Helene",
"Helmut Fritz - Ca m'enerve",
"Helmut Fritz - Ça m énerve 2020",
"Hervé Christiani - Il est Libre, Max [VIDEO]",
"Hervé Vilard - Capri C'est Fini",
"Hervé Vilard - Nous",
"Hoshi - Ta Marinière",
"Hugues Aufray - Adieu monsieur le professeur",
"Hugues Aufray - Santiano",
"Hélène Rolles - Pour l'amour d'un garçon",
"Hélène Ségara - Il Y A Trop De Gens Qui T'Aiment [VIDEO]",
"I Solisti Dell'Oltrepò Pavese - Bella Ciao",
"IAM - Le mia",
"Il était une fois - J'ai encore rêvé d'elle [MULTI]",
"Ilona Mitrecey - Un monde parfait",
"Images - Corps à corps",
"Images - Les Démons De Minuit",
"Images - Maitresse",
"Indila - Dernière danse",
"Indila - Parle à ta tête",
"Indila - Tourner dans le vide",
"Indochine - 3ème sexe",
"Indochine - J'ai Demandé A La Lune",
"Indochine - L'aventurier",
"Indochine - Tes yeux noirs",
"Indochine - Trois Nuits Par Semaine",
"Ivanov - Les nuits sans soleil",
"J.J.Lionel - La danse des canards",
"Jacques Dutronc - Et Moi Et Moi Et Moi",
"Jacques Dutronc - Fais pas ci fais pas ca",
"Jacques Dutronc - J aime les filles",
"Jacques Dutronc - L'Aventurier",
"Jacques Dutronc - Les cactus",
"Jean Dujardin - Le Casse de Brice [VIDEO]",
"Jean Pascal - La chanson con",
"Jean Schulteis - Confidence pour confidences",
"Jean-Jacques Goldman & Michael Jones - Je te donne",
"Jean-Jacques Goldman - Encore un Matin",
"Jean-Jacques Goldman - Envole-moi",
"Jean-Jacques Goldman - Il suffira d'un signe",
"Jean-Jacques Goldman - Quand la musique est bonne",
"Jean-Luc Lahaye - Femme que j'aime",
"Jean-Luc Lahaye - Papa Chanteur",
"Jean-Marc Anthony Kabeya - Pokemon",
"Jean-Pascal - L'agitateur",
"Jean-Pierre François - Je te Survivrai [VIDEO]",
"Jean-Pierre Mader - Disparue",
"Jean-Pierre Mader - Macumba",
"Jeanne Mas - En Rouge et Noir",
"Jeanne Mas - Johnny, Johnny",
"Jeanne Mas - Sauvez-moi",
"Jeanne Mas - Toute première fois",
"Jena Lee - J'aimerais tellement",
"Jenifer - Au Soleil",
"Jenifer - j'attends l'amour",
"Jessica Marquez - Maria Magdalena [VIDEO]",
"Jessy Matador & DJ Mam's & Luis Guisao - Zumba he zumba ha",
"Jessy Matador - Allez! Ola! Olé!",
"Joe Dassin - Et si tu n'existais pas",
"Joe Dassin - Les Champs-Elysées",
"Joe Dassin Le petit pain au chocolat",
"Johnny Hallyday - Allumer Le Feu",
"Johnny Hallyday - gabrielle",
"Johnny Hallyday - J'la croise tous les matins",
"Johnny Hallyday - Je Te Promets",
"Johnny Hallyday - L'Aventure C'Est L'Aventure",
"Johnny Hallyday - L'envie",
"Johnny Hallyday - Le Pénitencier",
"Johnny Hallyday - Ma gueule",
"Johnny Hallyday - Ma religion dans son regard",
"Johnny Hallyday - Noir C'est Noir",
"Johnny Hallyday - Oh ma jolie Sarah",
"Johnny Hallyday - Oh Marie",
"Johnny Hallyday - Pas cette chanson",
"Johnny Hallyday - Quand revient la nuit",
"Johnny Hallyday - Que je t'aime",
"Johnny Hallyday - Quelque Chose De Tennessee",
"Johnny Hallyday - Requiem pour un fou",
"Johnny Hallyday - Retiens la nuit",
"Johnny Hallyday - Sang pour sang",
"Johnny Hallyday - Toute La Musique Que J'aime",
"Johnny Hallyday - Vivre Pour Le Meilleur",
"Johnny Hallyday et Carmel - J'oublierai ton nom",
"Joyce Jonathan - Ca ira",
"Jul - l ovni",
"Jul - Wesh Alors",
"Julie Piétri - Eve lève toi",
"Julien Clerc - Fais-moi une place",
"Julien Clerc - Ma préférence",
"Julien Doré - Africa",
"K-Maro - Femme Like U [VIDEO]",
"Kamini - Marly Gomont",
"Kana - Ma Plantation",
"Karen Cheryl - Les nouveaux romantiques",
"Kate Ryan - Ella elle l'a",
"Kazero - Thai na na",
"Keen V & Lorelei B - La vie du bon cote",
"KEEN V - A l'horizontale",
"Keen V - J'aimerais trop",
"Keen V - Ma vie au soleil",
"Keen'v - Prince Charmant",
"Keen'V - Tahiti",
"Keen'V feat Carla - C'est bientôt noël",
"Kendji Girac & Claudio Capeo - Que Dieu me pardonne",
"Kendji Girac - Andalouse",
"Kendji Girac - Color Gitano",
"Kendji Girac - Cool",
"Kendji Girac - Dernier Métro (feat. GIMS)",
"Kendji Girac - Me Quemo",
"Kendji Girac - Petit papa Noël",
"Kendji Girac - Pour oublier",
"Kendji Girac - Tiago",
"Kendji Girac Soprano - No Me Mirès Màs",
"Kenjita Wurst - Travelo",
"Kenza Farah - Je Me Bats [VIDEO]",
"Kids United - On Ecrit Sur Les Murs",
"KidTonik - Aller plus loin",
"Kinito - Jsais Pas Danser",
"Koxie - Garcon",
"Kyo & Sita - Le chemin",
"Kyo - Dernière danse",
"Kyo - Je saigne encore",
"Kyo - Le Graal",
"L'algerino - Va bene",
"L5 - Toutes les femmes de ta vie",
"L5 - Une Etincelle",
"la bande à basile - La chenille",
"La Compagnie Créole - C'est bon pour le moral",
"La Compagnie Créole - Ca fait rire les oiseaux",
"La Compagnie Créole - Le bal masqué",
"La Plage - Coup de boule",
"La version Taloche - J'ai encore reve d'elle",
"Lagaf - Bo le lavabo",
"Lagaf la zoubida",
"Lara Fabian - Je t'aime",
"Lara Fabian - Tout",
"Laroche Valmont - T'as le look Coco",
"Lartiste - Catchu",
"Lartiste - Chocolat feat. Awa Imani",
"Lartisto ft Lady Djadja trop de nanana - Palmashow",
"Larusso - Tu m'oublieras",
"Laurent Voulzy - Derniers baisers",
"Laurent Voulzy - La fille d'avril",
"Laurent Voulzy - Les nuits sans Kim Wilde",
"Le Grand Orchestre Du Splendid - La Salsa Du Demon",
"Le Groupe Dallas - Dallas",
"Le prince des neiges Liberté - Palmashow (Frozen Parody)",
"Leopold Nord et Vous - C'est l'amour",
"Les Charts - Je m'envole",
"Les Chevaliers du Fiel - La Simca 1000",
"Les Choristes - Vois sur ton chemin",
"Les conards - Comme des conards",
"Les Cowboys Fringants - Plus rien",
"Les Enfoires - Attention au depart",
"Les enfoirés - La chanson des restos",
"Les entrechats",
"les fatals picards - bernard lavilliers",
"Les Fatals Picards - L'amour a la francaise",
"Les forbans - Chante",
"Les G.O. Culture - Darla Dirladada [VIDEO]",
"Les Inconnus (Douceur de Vivre) - CHANSON HARD ROCK (POÉSIE)",
"Les Inconnus - Auteuil Neuilly Passy",
"Les Inconnus - C'est Toi Que Je T'aime",
"Les Inconnus - Et Vice et Versa",
"Les inconnus - Isabelle a les yeux bleus",
"Les Inconnus - La Chanson De Biouman",
"Les Inconnus - Un chagrin d'amour",
"Les Minikeums - Ma Melissa",
"Les Muscles - La fete au village",
"Les Musclés - Allez Hop Boum Boum Crac Crac",
"Les musclés - avec Mozart",
"Les musclés - La Muscladance",
"Leslie - Boule de flipper",
"Licence IV - Viens boire un p'tit coup à la maison",
"Lio - Banana Split",
"Lio - Les Brunes [VIDEO]",
"Lorie - Ensorcelée",
"Lorie - J ai besoin d'amour",
"Lorie - Je serais",
"Lorie - Je Vais Vite [VIDEO]",
"Lorie - La positive attitude",
"Lorie - Sur un air Latino",
"Lorie - Toute seule",
"Lorie - Weekend [VIDEO]",
"Lorie - à 20 ans",
"Louane - Avenir",
"Louane - Je vole",
"Louane - Jour 1",
"Louane - Maman",
"Louise Attaque - J't'emmène au vent",
"Louise Attaque - Ton invitation",
"Luis Fonsdé & MC Roger - C'est l'apéro (Parodie Luis Fonsi)",
"Lynnsha feat. D. Dy - Hommes...femmes [VIDEO]",
"M. Pokora - De retour",
"M. Pokora - Les planètes",
"M. Pokora - Tombé",
"Magic System & Khaled - Meme pas fatigues",
"Magic System - Bouger Bouger",
"Magic System - Ki Dit Mié",
"Magic System - La danse des magiciens",
"Magic System feat Akil & Cheb Bilal & Big ali - C cho,Ca Brule",
"Maitre Gims - J’Me Tire",
"Maitre gims et Vitaa  - Game over",
"Manau - La Tribu de Dana",
"Manau - Mais Qui Est La Belette",
"Marc Lavoine - Elle a les yeux revolver",
"Marc Lavoine - La Semaine Prochaine",
"Marc Lavoine et Bambou - Dis-moi que l'amour",
"Marie Laforêt - Les vendanges de lamour",
"Matt Pokora - On danse",
"Maurane & Lara Fabian - Tu es mon autre",
"Max Boublil - ChatRoulette",
"Maître Gims - Bella",
"Maître Gims - Brisé",
"Maître Gims - Caméléon",
"Maître Gims - Changer",
"Maître Gims - Est-ce que tu m'aimes",
"Maître Gims - Hasta Luego",
"Maître GIMS - La Mme - En duo avec Vianney",
"Maître Gims - Laissez Passer",
"Maître Gims - Sapés comme jamais",
"Maître Gims - Tu vas me manquer",
"Maître Gims - Zombie",
"Maître GIMS Bella Ciao ft VITAA DADJU SLIMANE Naestro",
"MC Solaar - Bouge de Là [VIDEO]",
"MC Solaar - Hasta la Vista [VIDEO]",
"MC Solaar - Solaar Pleure [VIDEO]",
"Meli Melo - La Danse d'Hélène [VIDEO]",
"Menelik - bye bye",
"Michel Berger - La groupie du pianiste",
"Michel Berger - Le Paradis Blanc",
"Michel Berger - Quelques mots d'amour",
"Michel Delpech - Le Loir et Cher [VIDEO]",
"Michel Delpech - Pour un flirt",
"Michel Fugain - C'est la fête",
"Michel Fugain - Chante... comme si tu devais mourir demain",
"Michel Fugain - Une Belle Histoire",
"Michel Fugain - Viva La Vida",
"Michel Polnareff - Holidays",
"Michel Polnareff - La poupée qui fait non",
"Michel Polnareff - On ira tous au Paradis",
"Michel Sardou - Beethoven",
"Michel Sardou - En Chantant",
"Michel Sardou - Etre une femme",
"Michel Sardou - Je Vais T'aimer",
"Michel Sardou - Les deux ecoles",
"Michel Sardou - Les lacs du Connemara",
"Mika - Elle me Dit [VIDEO]",
"Mike Brant - Qui Saura [VIDEO]",
"Mikelangelo Loconte (Mozart L'Opéra Rock) - Tatoue-Moi",
"Mylene Farmer - Oui mais non",
"Mylene Farmer - Sans Contrefacon",
"Mylène Farmer - Ainsi Soit Je",
"Mylène Farmer - Appelle mon numéro",
"Mylène Farmer - C'est une belle journée",
"Mylène Farmer - Désenchantée",
"Mylène Farmer - Je Te Rends Ton Amour",
"Mylène Farmer - Libertine",
"Mylène Farmer - Maman a tort",
"Mylène Farmer - Pourvu qu'elles soient douces",
"Nadiya - Et c'est parti",
"Nadiya - Parle-moi",
"Nassi - La vie est belle",
"Natasha St Pier - Un Ange Frappe A Ma Porte",
"Natasha St-Pier - Tu Trouveras",
"Natasha St-Pier - Tu Trouveras [VIDEO]",
"Neg' Marrons - Le Bilan",
"Niagara - J'ai vu",
"Niagara - Je dois m'en aller",
"Niagara - L'Amour à La Plage",
"Niagara - Tchiki boum",
"Nino Ferrer - Le Téléfon",
"Nino Ferrer - Mirza",
"Noir Desir - Le vent nous portera",
"Notre Dame de Paris - Belle",
"Notre-Dame de Paris (Bruno PELLETIER) - Le temps des cathedrales",
"NTM - La fièvre",
"NZH - Princess",
"Nâdiya - Amies ennemies [VIDEO]",
"Nâdiya - Roc",
"Nâdiya - Tous Ces Mots",
"Olivia Ruiz - La femme chocolat",
"Ophélie Winter - Dieu m'a Donné la Foi",
"OrelSan - Basique",
"OrelSan - Tout va bien",
"OrelSan feat. Stromae - La pluie",
"Ottawan - Disco",
"Ottawan - T'es OK",
"Pacifique - Quand tu Serres mon Corps [VIDEO]",
"Palmashow - Ca mvénère",
"Partenaire particulier - Partenaire particulier",
"Pascal Danel -  Les neiges du Kilimenjaro",
"Pascal Danel - La plage aux romantiques",
"Pascal Obispo & Florent Pagny - Et un jour une femme",
"Pascal Obispo & Natasha St-Pier - Mourir demain",
"Pascal Obispo - Fan",
"Pascal Obispo - Millésime",
"Pascal Obispo - Tombé pour elle",
"Passi - Je Zappe Et Je Mate [VIDEO]",
"Patricia Kaas - Entrer dans la Lumière [VIDEO]",
"Patrick Bruel - Casser la voix",
"Patrick Bruel - Place des grands hommes",
"Patrick Coutin - J'aime regarder les filles",
"Patrick Juvet - Où sont les femmes",
"Patrick Sebastien - C'est chaud",
"Patrick Sebastien - Joyeux anniversaire",
"Patrick Sebastien - Le petit bonhomme en mousse",
"Patrick Sebastien - Les sardines",
"Patrick Sebastien - Tourner les serviettes",
"Patrick Sebastien - Une petite pipe",
"patrick sébastien - La fiesta",
"Patrick Sébastien - Pourvu que ça dure",
"Patrick Topaloff - J'ai bien mange, j'ai bien bu",
"Pauline - Allo Le Monde",
"Peter et Sloane - Besoin de rien, envie de toi [VIDEO]",
"Phenomenal Club - Il est vraiment phenomenal",
"Philippe Lavil - Il tape sur des bambous",
"Philippe Russo - Magie noire",
"Pierre Bachelet - En l'An 2001 [VIDEO]",
"Pierre Bachelet - Les Corons",
"Pierre Groscolas - Lady Lay",
"Pierre Perret - Le zizi",
"Pierre Perret - Les jolies colonies de vacances",
"Pierre Perrin - Un clair de lune à Maubeuge",
"Pigloo - Le papa pingouin",
"Pinocchio - T' Es Pas Cap Pinocchio",
"Plastic Bertrand - Ca plane pour moi",
"PLASTIC BERTRAND - HULA HOOP",
"Pomplamoose - Sous le Ciel de Paris",
"Poppys - Non non rien n'a changé",
"Pow Wow - Le lion est mort ce soir",
"Priscilla - Chante",
"Priscilla - Regarde-moi",
"PZK - Chuis Bo",
"PZK - Les Filles Adorent",
"Reciprok - Balance-toi",
"Remy Bricka - La vie en couleur",
"Renan Luce - La lettre",
"Renan Luce - Les voisines",
"Renaud & Axel Red - Manhattan-Kaboul",
"Renaud - Dès que le vent soufflera",
"Renaud - Laisse béton",
"Renaud - Mistral gagnant",
"Renaud - Toujours debout",
"Richard Anthony - Station service",
"Richard Gotainer - Le Youki",
"RIDSA - Dois-je men aller",
"RIDSA - Je m'en fous",
"RIDSA - Pardon",
"Robbie Neville - C'est la vie",
"Robin des bois - A nous - Marc Antoine",
"Rod Janois - Ca Ira Mon Amour",
"Roméo & Juliette - Aimer",
"Roméo et Juliette - Les Rois du monde",
"Saez - Jeune et Con",
"saian supa crew - angela",
"Serge Gainsbourg - Aux armes et caetera",
"Serge Gainsbourg - Couleur café",
"Serge Gainsbourg - Le Poinçonneur des Lilas",
"Serge Gainsbourg - Lemon Incest",
"Serge Lama - Je Suis Malade",
"Sheila - Gloria",
"Sheila - les rois mages",
"Sheila - no no no",
"Sheryfa Luna - Il Avait Les Mots [VIDEO]",
"Shy'm - Et alors",
"Shy'm - Femme de couleur",
"Shy'm - Il faut vivre",
"Shy'm - Je Sais",
"Shy'm - L'effet de serre",
"Shy'm - Prendre L'air",
"Shy'm - Silouette",
"Shy'm - Victoire",
"Sinsemilia - Tout le bonheur du monde",
"Slimane - Paname",
"Slimane - Viens on s'aime",
"Soeur Sourire - Dominique (disco remix)",
"Soprano - Clown",
"Soprano - Cosmo",
"Soprano - En feu",
"Soprano - Ferme les yeux et imagine toi",
"Soprano - Le Coach",
"Soprano - Le coeurdonnier",
"Soprano - Le diable ne s'habille plus en Prada",
"Soprano - Millionnaire",
"Soprano - Ninja",
"Soprano - Roule",
"Squeezie - Placements De Produits (feat. Maxenss)",
"Star Academy - La musique",
"Stromae - Alors on danse",
"Stromae - Carmen",
"Stromae - Formidable",
"Stromae - Papaoutai",
"Stromae - Tous Les Mêmes",
"Stéphanie - Ouragan",
"Superbus - Addictions [VIDEO]",
"Superbus - Apprends-Moi [VIDEO]",
"Superbus - Butterfly",
"Superbus - Ça Mousse [VIDEO]",
"Sylvie Vartan - Comme Un Garçon [VIDEO]",
"Sylvie Vartan - Deprime",
"Sébastien Patoche - La Cartouche",
"Sébastien Patoche - Quand Il Pète Il Troue Son Slip",
"Sébastien Patoche - Quand Il Pète Il Troue Son Slip [VIDEO]",
"Tal - Le sens de la vie",
"TAL - Le temps qu'il faut",
"Tal - Mondial",
"Tarmac - Notre epoque",
"Teri Moïse - Je serai là",
"Teri Moïse - Les poèmes de Michelle",
"Thierry Hazard - Le Jerk",
"Thomas Fersen - Deux pieds",
"Tina Arena - Aimer Jusqu'a L'impossible",
"Tina Arena - Aller plus haut",
"Tino Rossi - Mon beau sapin",
"Tino Rossi - Petit papa Noël",
"Tom Frager - Lady Melody",
"Tony Parker - Balance-toi",
"Tragedie -Sexy pour moi",
"Tragédie - Hey Oh",
"Tribal King - Façon sex",
"Trois Cafés Gourmands - Ainsi va la vie",
"Trois cafés gourmands - Comme des enfants",
"Trois cafés gourmands - Evidemment",
"Trois cafés gourmands - On t'emmène",
"Tropical Family - Maldon",
"Troudebal King - j'me tape ton ex",
"Trust - Antisocial",
"Tryo - Désolé pour hier soir",
"Tryo - Désolé pour hier soir (remix 2020)",
"Tryo - L'hymne de nos campagnes",
"Tuche Daddy feat. Tuche Daddy - Ça c'est Tuche Daddy !",
"Téléphone - Cendrillon",
"Téléphone - New York avec toi",
"Téléphone - Ça c'est vraiment toi",
"Téo Lavabo - Chipolata",
"Vanessa Paradis & M - La Seine  Animation",
"Vanessa Paradis - Joe le taxi",
"VEGEDREAM - RAMENEZ LA COUPE A LA MAISON",
"Vianney - Beau papa",
"Vianney - Dumbo",
"Vianney - Je m'en vais",
"Vianney - Moi aimer toi",
"Vianney - Pas là",
"Véronique Jannot et Laurent Voulzy  Desir desir - nouvelle version",
"Véronique Sanson - Chanson sur ma drole de vie",
"Véronique Sanson et Vianney - Chanson sur ma drôle de vie",
"Wazoo - La manivelle",
"Wejdene - Anissa",
"Wejdene - Coco",
"WhatFor - Plus Haut",
"William Balde - Rayon de soleil",
"Willy Denzey - Le Mur Du Son [VIDEO]",
"Willy William - Ego",
"Willy William feat. Keen'V - On s'endort [Clip Officiel]",
"Yannick - Ces soirees la",
"Yannick Noah - Destination ailleurs",
"Yannick Noah - Donne-moi une vie",
"Yannick Noah - La Voix des Sages (No more fighting)",
"Yannick Noah - Métis(se)  ft. Disiz La Peste",
"Yannick Noah - Saga Africa",
"Yelle - Je veux te voir [VIDEO]",
"Yelle - À cause des garçons",
"YVES LECOQ - ELLE JOUE DU PIPO COUCHEE",
"Yves Montand - La bicyclette",
"Zaz - Je veux",
"Zaz - On ira",
"Zaz - Tous les cris les SOS",
"Zazie - Je suis un homme",
"Zebda - Tomber La Chemise",
"Zouk Machine - Maldon",]


function en() {
    var randomNumber = Math.floor(Math.random()*(anglais.length));
    document.getElementById("gene").innerHTML = anglais[randomNumber];
    }
    
    
    function fr() {
    var randomNumber = Math.floor(Math.random()*(francais.length));
    document.getElementById("gene").innerHTML = francais[randomNumber];
    }
    
    